---
title: "LPS MIA accute"
author: "Raphael Kübler"
date: "04/14/2021"
output:
  rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true 
---

---

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(DESeq2)
library(xlsx)
library(Hmisc)
library(dplyr)
library(viridis)
library(pheatmap)
library(variancePartition)
library(RColorBrewer)
library(pcaExplorer)
library(vsn)
library(EnhancedVolcano)
library(DEGreport)
library(ggplot2)
library(ggpubr)


knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```

LPS-MIA base analysis
```{r load_packages, echo=FALSE}
library(DESeq2)
library(xlsx)
library(Hmisc)
library(dplyr)
library(viridis)
library(pheatmap)
library(variancePartition)
library(RColorBrewer)
library(pcaExplorer)
library(vsn)

options(check.names = FALSE)
```

#Load data
```{r load_data, echo=FALSE}
#Counts
dir <- file.path("C:", "Users", "rapha", "Dokumente", "UM FN", "Internship", "Internship_Start", "Side projects", "LPS bulk RNA-seq", "counts")
setwd(dir)

df <- read.table(file = "UMC-AB-b015_merged_R2.ReadCounts.tsv", sep = '\t', header = TRUE, row.names=1, check.names = F)

rownames(df) <- make.unique(gsub("__.*","",rownames(df)))


#Metadat
dir <- file.path("C:", "Users", "rapha", "Dokumente", "UM FN", "Internship", "Internship_Start", "Side projects", "LPS bulk RNA-seq", "metadata")
setwd(dir)

#Reading in metadata
library(readxl)
meta.df <- data.frame(read_excel("20200201_ABB_LPSproject_RNAseq_Metadata.xlsx"), check.names=F)

meta.df$`New sample name` <- paste(chartr(".", "-", meta.df$`Cell line`),meta.df$Batch,paste("D",meta.df$Day,sep=""),
                           paste(meta.df$Stimulation, meta.df$Duplicate, sep=""),sep="")

#Re-arranging the naming order of the various identifiers in order to match count data sample names with meta data sample names
n1 <- paste(chartr(".", "-", meta.df$`Cell line`),meta.df$Batch,paste("D",meta.df$Day,sep=""),
            meta.df$Stimulation,sep="")

meta.df$`New sample name`[n1 %in% colnames(df)] <- n1[n1 %in% colnames(df)]

n2 <- paste(chartr(".", "-", meta.df$`Cell line`),meta.df$Batch,
            meta.df$Stimulation,paste("D",meta.df$Day,sep=""),"_", meta.df$Duplicate,sep="")

meta.df$`New sample name`[n2 %in% colnames(df)] <- n2[n2 %in% colnames(df)]

n3 <- paste(chartr(".", "-", meta.df$`Cell line`),meta.df$Batch,
            paste(meta.df$Stimulation, meta.df$Duplicate, sep=""),sep="",paste("D",meta.df$Day,sep=""))

meta.df$`New sample name`[n3 %in% colnames(df)] <- n3[n3 %in% colnames(df)]

n4 <- paste(chartr(".", "-", meta.df$`Cell line`),meta.df$Batch,
            paste("D",meta.df$Day,sep=""),meta.df$Stimulation,"_", meta.df$Duplicate,sep="")

meta.df$`New sample name`[n4 %in% colnames(df)] <- n4[n4 %in% colnames(df)]

meta.df$`New sample name`[meta.df$`New sample name` %in% "OH1-5B4D66LPS1"] <- colnames(df)[!colnames(df) %in% meta.df$`New sample name`]


#Set new rownames
rownames(meta.df) <- meta.df$`New sample name`


meta.df$Stimulation <- relevel(as.factor(meta.df$Stimulation),"CTR")
meta.df$Batch <- as.factor(as.numeric(as.factor(meta.df$Batch)))
meta.df$`Cell line` <- as.factor(meta.df$`Cell line`)
meta.df$`Accute/chronic` <- as.factor(meta.df$`Accute/chronic`)
meta.df$Replicate <- meta.df$Replicate
meta.df <- meta.df[sort(meta.df$`New sample name`),]

df <- df[sort(colnames(df))]

#Subsetting the df to only the samples present in the count matrix
meta.df.sub <- meta.df[meta.df$`New sample name` %in% colnames(df),]

#Creating a new metadata file with additional covariates
meta.df.sub$`Percent. ERCC` <- colSums(x = df[grep(pattern = "^ERCC-", x = rownames(df), value = TRUE), 
                                           drop = FALSE,])/colSums(df) * 100
meta.df.sub$`Percent. MT` <- colSums(x = df[grep(pattern = "^MT-", x = rownames(df), value = TRUE), 
                                         drop = FALSE,])/colSums(df) * 100
meta.df.sub$`Library size` <- colSums(df)
meta.df.sub$Experiment <- as.factor(paste("Cell line_",meta.df.sub$'Cell line',"_Batch_",meta.df.sub$Batch,sep="_"))

#Check whether sample names are in correct order
identical(rownames(meta.df.sub), colnames(df))

```

#Writing functions
```{r functions, echo=FALSE}
IQRoutlier.detector <- function(df, barplot=T){
  d <- rcorr(as.matrix(df), type="pearson")
  
  barplot.df <- data.frame(Intersample.correlation=c(rowMeans(d$r), rowMedians(d$r)), 
                           Metric=c(rep("Correlation Means",
                                        length(colnames(d$r))), rep("Correlation Medians", length(colnames(d$r)))))
  if(barplot){
    #700 x 470
    outlier.barplot <- 
      barplot.df %>% 
      ggplot( aes(x=Metric, y=Intersample.correlation, fill=Metric)) +
      geom_boxplot() +
      scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
      geom_text(aes(label=c(rownames(d$r), rownames(d$r))))+
      theme(
        legend.position="Type",
        plot.title = element_text(size=11)
      ) +
      #  ggtitle("Boxplots showing outliers based on inter-sample correlation means and medians before data correction") +
      theme_bw()+
      theme(plot.title = element_text(hjust=0.5))+
      xlab("")+
      #geom_hline(yintercept=median(d_core)-3*mad(d_core),  linetype="dashed")+
      geom_segment(aes(x=1.7,xend=2.3,y=ifelse(median(d$r)-3*mad(d$r) < -1, -1, median(d$r)-3*mad(d$r)),yend=ifelse(median(d$r)-3*mad(d$r) < -1, -1, median(d$r)-3*mad(d$r))),color="red", linetype="dashed")+
      geom_segment(aes(x=1.7,xend=2.3,y=ifelse(median(d$r)+3*mad(d$r) > 1, 1, median(d$r)+3*mad(d$r)),yend=ifelse(median(d$r)+3*mad(d$r) > 1, 1, median(d$r)+3*mad(d$r))),color="red", linetype="dashed")+
      geom_segment(aes(x=0.7,xend=1.3,y=ifelse(mean(d$r)-3*sd(d$r) < -1, -1, mean(d$r)-3*sd(d$r)),yend=ifelse(mean(d$r)-3*sd(d$r) < -1, -1, mean(d$r)-3*sd(d$r))),color="red", linetype="dashed")+
      geom_segment(aes(x=0.7,xend=1.3,y=ifelse(mean(d$r)+3*sd(d$r) > 1, 1, mean(d$r)+3*sd(d$r)),yend=ifelse(mean(d$r)+3*sd(d$r) > 1, 1, mean(d$r)+3*sd(d$r))),color="red", linetype="dashed")
    return(outlier.barplot)}
  else {
    outlier.heatmap <- pheatmap(d$r)
    return(outlier.heatmap)
  }
}

#PCA
plotPCA.custom <- function (object, intgroup = "condition", ntop = 44099, returnData = TRUE, metadata = metadata, pc.1=1, pc.2=2) 
{
  rv <- rowVars(object)
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(object[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% colnames(metadata))) {
    stop("the argument 'intgroup' should specify columns of metadata")
  }
  intgroup.df <- data.frame(metadata[intgroup],check.names=F)
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = ":"))
  }
  else {
    metadata[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, pc.1], PC2 = pca$x[, pc.2], group = group, 
                  intgroup.df, name = colnames(object), check.names=F)
  if (returnData) {
    attr(d, "percentVar") <- percentVar[c(pc.1,pc.2)]
    return(d)
  }
  ggplot(data = d, aes_string(x = paste("PC",pc.1), y = paste("PC",pc.2), 
                              color = "group")) + geom_point(size = 3) + xlab(paste0(paste("PC", pc.1, ": ", sep=""),
                                                                                     round(percentVar[1] * 100), "% variance")) + ylab(paste0(paste("PC", pc2, ": ", sep=""), 
                                                                                                                                              round(percentVar[2] * 100), "% variance")) + coord_fixed()
}

#Plot PCA (ggplot)
PCAplot <- function(pca.df, Condition, Shape=NULL, pc.1=1, pc.2=2, PoV.df, colors=c("#00AFBB", "#E7B800", "#FC4E07")){
  if(!is.null(Shape))
    ggplot(pca.df, aes(PC1, PC2, color=pca.df[[c(Condition)]], label=name)) +
      geom_point(size=2, aes(shape=pca.df[[Shape]]))+
      labs(x = paste0("PC", paste(pc.1), ": ", PoV.df[1], "% variance"), y = paste0("PC", paste(pc.2), ": ",PoV.df[2],"% variance"), 
         color = Condition, shape=Shape) +  
      scale_color_manual(values = colors)+
      theme_bw()+
      theme(plot.title = element_text(hjust=0.5))
  else
    ggplot(pca.df, aes(PC1, PC2, color=pca.df[[c(Condition)]], label=name)) +
      geom_point(size=2)+
      labs(x = paste0("PC", paste(pc.1), ": ", PoV.df[1], "% variance"), y = paste0("PC", paste(pc.2), ": ",PoV.df[2],"% variance"), 
         color = Condition) +  
      scale_color_manual(values = colors)+
      theme_bw()+
      theme(plot.title = element_text(hjust=0.5))
}



#Density plot
plot.density <- function(meta.df,to.color="Condition",to.plot="Library size",ylab.title="Density",xlab.title="Library size"){
  meta.df %>% 
    ggplot(aes_string(color=to.color, x=to.plot, fill=to.color)) + 
    geom_density(alpha = 0.2) + 
    scale_x_log10() + 
    theme_classic() +
    ylab(ylab.title) +
    xlab(xlab.title)
}

#Histogram
plot.hist <- function(data.to.plot,log10ofdat=T,xlab.title="Data",
                      main.title="Counts of X",ylab.title="Number of samples",color="grey80",
                      thresh1=1,thresh2=10){
  if (log10ofdat)
    log.data <-log10(data.to.plot)
  hist(log.data, xlab=xlab.title, 
       main=paste(main.title, "mean = ", round(mean(data.to.plot),2), ";",
                  "median = ", round(median(data.to.plot),2)), 
       breaks=20, col=color, ylab=ylab.title)
  abline(v = thresh1, col="red", lwd=3, lty=2)
  abline(v = thresh2, col="red", lwd=3, lty=2)
}

#Function for covar-PC correlation
#function for PCA
PCA.covar <- function(df, meta, heatmap.r=F, data.r=F, heatmap.p=T,type="spearman"){
  pca.cov <- prcomp(t(df))
  PC.covs <- pca.cov$x[,1:15]
  PC_cov_correlation <- rcorr(as.matrix(PC.covs), as.matrix(meta), type=type)
  PC_variance.explained <- PC_cov_correlation$r[1:15,16:length(rownames(PC_cov_correlation$r))]
  PC_cov.cor.p <- PC_cov_correlation$P[1:15,16:length(rownames(PC_cov_correlation$r))]
  if (heatmap.r)
    pheatmap(PC_variance.explained, cluster_rows = F, cluster_cols = F, show_colnames = T,
             color = heatmap.color.code)
  if (heatmap.p)
    pheatmap(PC_cov.cor.p, cluster_rows = F, cluster_cols = F, show_colnames = T,
             color = colorRampPalette(c("red", "white"))(50),
             display_numbers = T)
  if (data.r)
    return (PC.covs)
}
```

(0) Pre-processing
```{r pre-processing, echo=FALSE}
#Filtering
#filt.meta <- meta.df.sub[meta.df.sub$Library size > 500000 & meta.df.sub$Library size < 15000000,] #remove large library size-samples
filt.meta <- meta.df.sub[meta.df.sub$`Library size` > 500000,] #removes no samples
filt.df <- df[colnames(df) %in% rownames(filt.meta)]


#Filtering based on MT RNA content
filt.meta <- filt.meta[filt.meta$`Percent. MT` < 20,] #removes no samples
filt.df <- df[colnames(df) %in% rownames(filt.meta)]

#Gene filtering
g.filter <- rowSums(filt.df) > quantile(rowSums(filt.df), 0.15)
gfilt.df <- filt.df[g.filter,]

#Sorting
gfilt.df <- gfilt.df[sort(colnames(gfilt.df),decreasing=T)]

filt.meta <- filt.meta[sort(rownames(filt.meta), decreasing=T),]

#Sanity check:
#identical(colnames(gfilt.df),rownames(filt.meta))

#'Library size'
filt.meta$'Library size post filter' <- colSums(gfilt.df)

```

#Loading data
Plotting the first QC results (post-filter QC):

(1) Density plots
```{r plots.1, echo=FALSE}
#Density plot
#library size
plot.density(filt.meta,to.color="Stimulation",to.plot="log10(`Library size`)")

#mtRNA
plot.density(filt.meta,to.color="Stimulation",to.plot="`Percent. MT`",xlab.title="mtRNA percentage")

#ERCC
plot.density(filt.meta,to.color="Stimulation",to.plot="`Percent. ERCC`",xlab.title="ERCC proportion")


```

(2) IQR and inter-sample distances on PCA
```{r plots.2, echo=FALSE}

#Outlier detection based on IQR correlation
sOutliers.filt <- IQRoutlier.detector(gfilt.df,barplot=T)
sOutliers.filt

pca <- plotPCA.custom(as.matrix(filt.df), intgroup=c("Cell line", "Batch","Accute/chronic", "Stimulation"), ntop = 50000, returnData=TRUE, 
                      metadata=filt.meta)
PoV <- round(100 * attr(pca, "percentVar"))
PCAplot(pca, "Accute/chronic", Shape="Stimulation", PoV.df=PoV)
PCAplot(pca, "Cell line", Shape="Batch", PoV.df=PoV)
```

(3) Covariate correlation
```{r plots.3, echo=FALSE}
#Changing factors to factors
filt.meta$Duplicate <- as.factor(filt.meta$Duplicate)
filt.meta$Stimulation <- as.factor(filt.meta$Stimulation)
filt.meta_clean <- filt.meta[!colnames(filt.meta) %in% c("Duplicate","Sample NR","New sample name","Day","Library size post filter","Condition","Sample Name")]

filt.meta_clean$'Library size' <- log(filt.meta_clean$'Library size')

#====Colinearity analysis of covariates====#
heatmap.color.code <- rev(brewer.pal(11,"RdYlBu"))
#Check co-linearity of covariates for subsetted samples
cov_for.cor <- filt.meta_clean
cov_for.cor$Experiment <- as.factor(as.numeric(cov_for.cor$Experiment))
cov_for.cor$Stimulation <- as.factor(as.numeric(cov_for.cor$Stimulation))
cov_for.cor$Replicate <- as.factor(as.numeric(as.factor(cov_for.cor$Replicate)))
cov_for.cor$`Accute/chronic` <- as.factor(as.numeric(as.factor(cov_for.cor$`Accute/chronic`)))
cov_for.cor$'Cell line' <- as.factor(as.numeric(cov_for.cor$'Cell line'))
covar.cor.all <- rcorr(as.matrix(cov_for.cor), type="spearman")
covar.cor <- covar.cor.all$r

#Covariate correlation
pheatmap(covar.cor, color = heatmap.color.code)


```

(4) PC-covariate correlation
```{r plots.4, echo=FALSE}

#====PC loadings for covariates====#
identical(colnames(gfilt.df), rownames(cov_for.cor))
PCA.covar(gfilt.df,cov_for.cor,data.r=F)

```
